services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food_delivery_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src/data:/app/src/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food_delivery_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
